### PR TITLE
Add bit length option to create_ssh_key

### PR DESCRIPTION
**Pull request by esalberg**
Add a new parameter to allow setting the bit length of the new key.

### CODE REVIEW

**Comment by esalberg** [comment]
Please let me know if you'd prefer for me to implement this with one exec instead - I thought about doing that, but it would have required determining the defaults for the ssh-keygen command (across different platforms, etc.).  While this isn't the most elegant way, at least it preserves backwards compatibility for taking the default.

**Comment by jtopjian** [comment]
What's your opinion on a good default bit length regardless of platform? I'm OK with setting/enforcing a modern size by default, and the user can always make it lower if they want to.

**Comment by jtopjian** [comment]
And in general, it's pretty safe to play around with this exec statement since it only runs if a key doesn't exist, so this _shouldn't_ overwrite any existing key pair.

**Comment by esalberg** [comment]
Good point about not overwriting keys...although I always worry about consistency for new servers that might be built into an existing configuration (e.g. on a different / older platform).

From an extremely quick Google:
http://serverfault.com/questions/40071/ssh-keypair-generation-rsa-or-dsa

So per ssh-keygen:
 Specifies the number of bits in the key to create.  For RSA keys,
   the minimum size is 768 bits and the default is 2048 bits.  Gen-
   erally, 2048 bits is considered sufficient.  DSA keys must be
   exactly 1024 bits as specified by FIPS 186-2.

I've seen other comments that with new protocols, it's okay to have larger DSA keys.  Ideally, the best option would be to have two defaults, one if RSA is selected, and one if DSA is selected (I'm not even touching ECDSA right now).

I would probably implement this with something like the following (a bit convoluted since Puppet doesn't allow reassigning of variables; please excuse the formatting).  Your call - let me know if you want to stay with the if statement and double execs or have me refactor it this (or another) way.

---------------------------------------
( ...
sshkeytype = 'rsa',
bitlength      = undef,
)

$rsa_default='2048'
$dsa_default='1024'

case $sshkeytype:
   'rsa': { if $bitlength { $sshbits = $bitlength } else { $sshbits = $rsa_default } }
   'dsa': { if $bithlength { $sshbits = $bitlength } else { $sshbits = $dsa_default } }
      
[everything else stays as is - one exec resource, etc.]

**Comment by jtopjian** [comment]
Yeah, I'm thinking the added logic outweighs the two execs... I think in the log run, it would prevent the possibility of future patches forgetting to update both execs.

**Comment by esalberg** [comment]
The code has been refactored - I  also update the readme / comments and the spec tests.  Please let me know if it needs any further changes.

**Comment by jtopjian** [comment]
:+1: 

Thank you for updating the spec as well.

**Pull request merged**
